version: "3"

services:
  flask:
    build:
      context: ./flask
    restart: always
    container_name: flask
    expose:
      - 5000
    networks:
      my-network:
        aliases:
          - flask-app

  nginx:
    build:
      context: ./nginx
    restart: always
    networks:
      - my-network
    depends_on:
      - flask
    ports:
      - "80:80"
  
  
networks:
  my-network: